### Create and Update CDA maps for converting to FHIR with RESTClient and running matchbox
### Note: POST the maps in the following order, if you update one map you need to repost also the maps below

#@host = https://test.ahdis.ch/r4
@host = http://localhost:8080/r4
#@host = http://localhost:8080/matchbox/fhir

# Own matchbox instance
#@host = http://bmpqadocker.cloud.blacktusk.eu:8087/r4

### Capability Statement
GET {{host}}/metadata HTTP/1.1
Content-Type: application/fhir+json;fhirVersion=4.0

### StructureMap-Ressorces ---------------------------------------------------------------------

### 1. POST CDA2FHIRTypes.map - using embedded ConceptMaps
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0.1
Content-Type: text/fhir-mapping

< ./maps/CDA2FHIRTypes.map

### 1a. POST CDA2FHIRLaboratoryReport.map (completist approach) - not finished
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0.1
Content-Type: text/fhir-mapping

< ./maps/completist/CDA2FHIRLaboratoryReport.map

### 1b. POST CDA2FHIRDiagnosticReport.map (selective approach) - using embedded ConceptMaps
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0.1
Content-Type: text/fhir-mapping

< ./maps/selective/CDA2FHIRDiagnosticReport_v220.map

### Execution of Transformation ----------------------------------------------------------------------

### 2a. POST Mikrobiologischer_Befund_3.0.0.xml (completist approach) - not finished
POST {{host}}/StructureMap/$transform?source=http://hl7.org/fhir/cda2fhir/StructureMap/CDA2FHIRCompositionLaboratoryReport
Accept: application/fhir+xml;fhirVersion=4.0.1
Content-Type: application/fhir+xml;fhirVersion=4.0.1

< ./input/Mikrobiologischer_Befund_2.06.04.xml

### 2b. POST Mikrobiologischer_Befund_3.0.0.xml (selective approach)
POST {{host}}/StructureMap/$transform?source=http://hl7.org/fhir/cda2fhir/StructureMap/CDA2FHIRDiagnosticReport
Accept: application/fhir+xml;fhirVersion=4.0.1
Content-Type: application/fhir+xml;fhirVersion=4.0.1

< ./input/Mikrobiologischer_Befund_teilweise_3.0.0.xml

### Validation of Transformation ----------------------------------------------------------------------

### 3a. POST Transformation Result
POST https://server.fire.ly/$validate
Accept: application/fhir+xml;fhirVersion=4.0
Content-Type: application/fhir+xml;fhirVersion=4.0

< ./output/FHIR_Bundle.xml

### 3b. GET Validate Code
#GET https://server.fire.ly/administration/ValueSet/$validate-code?system=http://hl7.org/fhir/ValueSet/diagnostic-service-sections&code=MB&display=Microbiology
#GET https://server.fire.ly/administration/ValueSet/diagnostic-service-sections/$validate-code?code=MB
GET https://server.fire.ly/administration/ValueSet/diagnostic-service-sections/$validate-code?code=LAB



